version: '3.3'

services:
    backend:
      build:
        context: .
        dockerfile: Dockerfile
      image: maddytec/soniflores-gateway:1.0
      ports:
        - 8080:8080
      network_mode: "host"