eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    lease-renewal-interval-in-seconds: 5

zuul:
  routes:
    index:
      sensitiveHeaders:
      path: /usuario/login
      url: http://127.0.0.1:8090/
    usuario:
      sensitiveHeaders:
      path: /usuario/**
      url: http://127.0.0.1:8090/usuario/
    grupo:
      sensitiveHeaders:
      path: /grupo/**
      url: http://127.0.0.1:8090/grupo/
    produto:
      sensitiveHeaders:
      path: /produto/**
      url: http://127.0.0.1:8091/produto/
    produto-consulta:
      sensitiveHeaders:
      path: /produto-consulta/**
      url: http://127.0.0.1:8091/produto-consulta/
    categoria:
      sensitiveHeaders:
      path: /categoria/**
      url: http://127.0.0.1:8091/categoria/
    categoria-consulta:
      sensitiveHeaders:
      path: /categoria-consulta/**
      url: http://127.0.0.1:8091/categoria-consulta/
    cliente:
      sensitiveHeaders:
      path: /cliente/**
      url: http://127.0.0.1:8092/cliente/
      cliente-consulta:
        sensitiveHeaders:
        path: /cliente-consulta/**
        url: http://127.0.0.1:8092/cliente-consulta/
